# autogenerated sources_list.cmakefor project(dummy_project)

set(GROUP_CORE_SRC_HELPERS
		Core/Src/helpers/my_comm.c
		Core/Src/helpers/xprintf.c
)

set(GROUP_CORE_SRC_LAN
		Core/Src/lan/enc28j60.c
		Core/Src/lan/lan.c
)

set(GROUP_CORE_SRC_MANCHESTER
		Core/Src/manchester/manchester.c
)

set(GROUP_CORE_SRC_MQTTSNPACKET
		Core/Src/MQTTSNPacket/MQTTSNConnectClient.c
		Core/Src/MQTTSNPacket/MQTTSNConnectServer.c
		Core/Src/MQTTSNPacket/MQTTSNDeserializePublish.c
		Core/Src/MQTTSNPacket/MQTTSNPacket.c
		Core/Src/MQTTSNPacket/MQTTSNSearchClient.c
		Core/Src/MQTTSNPacket/MQTTSNSearchServer.c
		Core/Src/MQTTSNPacket/MQTTSNSerializePublish.c
		Core/Src/MQTTSNPacket/MQTTSNSubscribeClient.c
		Core/Src/MQTTSNPacket/MQTTSNSubscribeServer.c
		Core/Src/MQTTSNPacket/MQTTSNUnsubscribeClient.c
		Core/Src/MQTTSNPacket/MQTTSNUnsubscribeServer.c
)

set(GROUP_CORE_SRC_NTP
		Core/Src/ntp/ntp.c
)

set(GROUP_CORE_SRC_NVMEM
		Core/Src/nvmem/nvmem.c
)

set(GROUP_CORE_SRC_TFTP
		Core/Src/tftp/TFTP_ser_desesr.c
		Core/Src/tftp/mystrcpy.c
		Core/Src/tftp/tftp_server.c
)

set(GROUP_CORE_SRC_TINY-FS
		Core/Src/tiny-fs/tiny-fs.c
)

set(GROUP_CORE_SRC
		Core/Src/adc.c
		Core/Src/crc.c
		Core/Src/dma.c
		Core/Src/freertos.c
		Core/Src/gpio.c
		Core/Src/i2c.c
		Core/Src/iwdg.c
		Core/Src/main.c
		Core/Src/rtc.c
		Core/Src/spi.c
		Core/Src/stm32f1xx_hal_msp.c
		Core/Src/stm32f1xx_hal_timebase_tim.c
		Core/Src/stm32f1xx_it.c
		Core/Src/system_stm32f1xx.c
		Core/Src/tim.c
		Core/Src/usart.c
)

set(GROUP_DRIVERS_STM32F1XX_HAL_DRIVER_SRC
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_crc.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_iwdg.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c
		Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c
)

set(GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE_CMSIS_RTOS
		Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c
)

set(GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE_PORTABLE_GCC_ARM_CM3
		Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3/port.c
)

set(GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE
		Middlewares/Third_Party/FreeRTOS/Source/croutine.c
		Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
		Middlewares/Third_Party/FreeRTOS/Source/list.c
		Middlewares/Third_Party/FreeRTOS/Source/queue.c
		Middlewares/Third_Party/FreeRTOS/Source/tasks.c
		Middlewares/Third_Party/FreeRTOS/Source/timers.c
)
include_directories(Core/Inc)
include_directories(Core/Inc/MQTTSNPacket)
include_directories(Core/Inc/helpers)
include_directories(Core/Inc/lan)
include_directories(Core/Inc/manchester)
include_directories(Core/Inc/ntp)
include_directories(Core/Inc/nvmem)
include_directories(Core/Inc/tftp)
include_directories(Core/Inc/tiny-fs)
include_directories(Drivers/CMSIS/Device/ST/STM32F1xx/Include)
include_directories(Drivers/CMSIS/Include)
include_directories(Drivers/STM32F1xx_HAL_Driver/Inc)
include_directories(Drivers/STM32F1xx_HAL_Driver/Inc/Legacy)
include_directories(Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS)
include_directories(Middlewares/Third_Party/FreeRTOS/Source/include)
include_directories(Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3)

set(LIST_OF_SOURCES
		${GROUP_CORE_SRC}
		${GROUP_CORE_SRC_HELPERS}
		${GROUP_CORE_SRC_LAN}
		${GROUP_CORE_SRC_MANCHESTER}
		${GROUP_CORE_SRC_MQTTSNPACKET}
		${GROUP_CORE_SRC_NTP}
		${GROUP_CORE_SRC_NVMEM}
		${GROUP_CORE_SRC_TFTP}
		${GROUP_CORE_SRC_TINY-FS}
		${GROUP_DRIVERS_STM32F1XX_HAL_DRIVER_SRC}
		${GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE}
		${GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE_CMSIS_RTOS}
		${GROUP_MIDDLEWARES_THIRD_PARTY_FREERTOS_SOURCE_PORTABLE_GCC_ARM_CM3}
)
