#ifndef TASK_TOKENS_H
#define TASK_TOKENS_H

#define MAGIC_SEED	1U

#define	LAN_POLL_TASK_MAGIC	(uint32_t)(MAGIC_SEED)
#define LOGGER_TASK_MAGIC	(uint32_t)(MAGIC_SEED + 1U)
#define MANCHESTER_TASK_MAGIC	(uint32_t)(MAGIC_SEED + 2U)
#define PUB_TASK_MAGIC		(uint32_t)(MAGIC_SEED + 3U)
#define SUB_TASK_MAGIC		(uint32_t)(MAGIC_SEED + 4U)
#define SERVICE_TASK_MAGIC	(uint32_t)(MAGIC_SEED + 5U)
#define OPENTHERM_TASK_MAGIC	(uint32_t)(MAGIC_SEED + 6U)

#endif // TASK_TOKENS_H
